name: Build and Deploy to dockerhub

on:
    push:
        branches:
            - master

jobs:
    build-and-push:
      name: Build and Push Docker Image
      runs-on: ubuntu-latest

      steps:
        # Step 1: Check out the code
        - name: Checkout Code
          uses: actions/checkout@v3
        
        # Step 2: Log in to Docker Hub
        - name: Log in to Docker Hub
          uses: docker/login-action@v3
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

        # Step 3: Build and Push Docker image
        - name: Build and Push Docker image
          uses: docker/build-push-action@v6
          with:
              context: .
              file: ./docker/app-docs/Dockerfile
              push: true
              tags: ${{ secrets.DOCKER_USERNAME }}/docs-next-app:${{ github.sha }}
        
        # Step 4: Verify Pushed Image
        - name: Verify Pushed Image
          run: docker pull ${{ secrets.DOCKER_USERNAME }}/docs-next-app:${{ github.sha }}